sudo: required

services:
  - docker

matrix:
  include:
    - if: branch =~ back

      env:
        - STAGE=beta
    
      script: cd back && ./build-docker.sh

    - if: branch =~ front

      env:
          - STAGE=beta
    
      script: cd front && ./build-docker.sh

    - if: branch =~ master

      env:
          - STAGE=prod
    
      script: cd front && ./build-docker.sh && cd .. && cd back && ./build-docker.sh
